services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    image: sagarkumarrana/portfolio:latest
    container_name: cyberpunk_portfolio
    restart: always
    ports:
      - "127.0.0.1:3001:80"
    environment:
      - NODE_ENV=production
